{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    "@semantic-release/changelog",
    [
      "@semantic-release/npm",
      {
        "npmPublish": false
      }
    ],
    {
      "path": "@semantic-release/git",
      "assets": [
        "package.json",
        "pnpm-lock.json",
      ],
      "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
    }
  ],
  "branches": [
    "master",
  ]
}