version: '3.8'

services:
  app:
    container_name: job_board_server
    image: job_board_server
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 4000:4000
  database:
    container_name: job_board_db
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_board_dev
    ports:
      - 5432:5432
